### ISSUE TITLE
Non-Serbian characters are deleted

### ISSUE THREAD

**Issue by Trey314159** [vukbatanovic/SCStemmers#1]
(I would like to wrap these stemmers into an Elasticsearch analysis plugin for use on Wikipedia, Wiktionary, and other Serbian, Croatian, Serbo-Croatian, and possibly Bosnian wiki projects. However there are some issues that prevent that from happening.)

I believe that [these lines](https://github.com/vukbatanovic/SCStemmers/blob/be89c7a26e188630761d22c2125e068643b8d56a/src/weka/core/stemmers/KeseljSipkaStemmer.java#L84-L85) and similar in other stemmers are causing a big problem for non-Serbian text.

For example, तथा is made up of त + थ +  ा; the first two characters are letters according to Java, while the last character is not a letter. So, तथा gets stemmed as " ा". Words that are all non-Serbian characters that Java recognizes as letters, like ऊपर, get stemmed as an empty string. This happens to lots of other writing systems besides Devanagari (Hindi), including Greek, Armenian, Hebrew, Arabic, Japanese, Chinese, Korean, and many others (all of which are common in Wikipedia and Wiktionary).

Similarly, words with non-Serbian Latin or Cyrillic letters get stemmed very oddly. ğaʿala, ḍaẓaġ, and ṯaẖaḏ all get stemmed as "aa", mostly because several letters are dropped. Эмин is stemmed as "min" because the initial Э is ignored.

**Comment by Trey314159** [comment]
I've submitted a pull request to fix this issue: https://github.com/vukbatanovic/SCStemmers/pull/3

**Comment by vukbatanovic** [comment]
Thanks for the correction! I must admit that during the re-implementation of the stemmers provided in this package I did not really pay attention to their behavior on non-Serbian/Croatian texts.

**Comment by Trey314159** [comment]
Glad to help! Working with Wikipedia data I've gotten used to assuming that every Unicode character there is could possibly show up in the text. Every so often I have to install new fonts for character sets I hadn't previously heard of. It's great fun.
