### ISSUE TITLE
suffix transformation can transform non-suffixes

### ISSUE THREAD

**Issue by Trey314159** [vukbatanovic/SCStemmers#4]
The [suffix transformation](https://github.com/vukbatanovic/SCStemmers/blob/master/src/weka/core/stemmers/LjubesicPandzicStemmer.java#L131) in the Ljubešić-Pandžić stemmer is not restricted to only modifying the suffix.

I couldn't find a real world Serbian or Croatian word that had the problem, but the name "Kovačevac" does show up in URLs, for example, without diacritics as "kovacevac", and both instances of "vac" get changed to "vca", giving the final output as "kovcaevc", rather than "kovacevc".

I didn't test it, but looking at the original Python source, it seems to limit substitutions to just suffixes.

**Comment by vukbatanovic** [comment]
Good catch! Fixed in v1.1.1
